---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: conduit-inject
  name: conduit-inject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conduit-inject
      name: conduit-inject
    spec:
      containers:
        - name: webhook
          image: gcr.io/rmars/mutating-webhook:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: webhook
  name: webhook
spec:
  ports:
    - port: 443
      targetPort: 8080
  selector:
    app: conduit-inject
